### PR TITLE
Implement yield

### PR DESCRIPTION
**Pull request by bethesque**
Added ability to provide block to open method so it can be used in the same way as HTTP URIs.

### CODE REVIEW

**Comment by pepijn** [comment]
:+1:

**Comment by bethesque** [comment]
Thanks for merging the other pull request. Did you intentionally not merge this one? I'm quite keen to have this functionality, as it means we can treat open the same way for s3 as for other URIs.

**Comment by eterps** [comment]
Ah sorry, I was under the impression that I did merge it (github didn't support an automatic merge and apparently I did something wrong). This commit should fix it: https://github.com/eterps/open-uri-s3/commit/a3586b6e60525d98f8fd73b61fba9f65a13011f2

**Comment by bethesque** [comment]
Thought it might have been an accident. Thanks!

**Pull request closed without merging**
